### ISSUE TITLE
e9compiled modules fail

### ISSUE THREAD

**Issue by farimani** [GJDuck/e9patch#25] opened 2021-09-15 07:11 UTC
I'm having problems with arguments passed into a simple instrumentation module, so I tried the pretty print example and it segfaults. I put the example in a Dockerfile so you can hopefully reproduce easily:

Dockerfile:

```
FROM debian:stretch                                                                                                     
RUN apt update && apt install build-essential vim xxd git -y                                                            
RUN git clone https://github.com/GJDuck/e9patch.git && cd /e9patch && ./build.sh && ./e9compile.sh examples/print.c     
WORKDIR /e9patch                                                                                                        
RUN echo '#include <stdio.h>\n' \                                                                                       
         'int main() {\n' \                                                                                             
         '    printf("hello world!\\n");\n' \                                                                           
         '    return 0;\n' \                                                                                            
         '}\n' > hello.c                                                                                                
RUN gcc -static hello.c -o hello                                                                                        
RUN ./e9tool -M 'asm=syscall' -A 'call entry(addr,instr,size,asm)@print' hello                                          
```

Save as "Dockerfile" in an empty folder, cd into it, and build the docker image:

`docker build -t e9deb .`

Bash into it:

`docker run --rm -it e9deb`

Once inside the container, run the resulting ./a.out and it segfaults.

**Comment by GJDuck** [comment] 2021-09-15 07:39
The problem is that `stdlib.c` assumes the program is dynamically linked by default, but in this case the binary is statically linked.  It can be fixed with some more magic:

    ./e9compile.sh examples/print.c -DNO_GLIBC=1

I probably need to address this, since it is non-obvious what the problem was and how to fix it.

**Comment by farimani** [comment] 2021-09-15 15:32
Thank you that works like magic!

**Closed** 2021-09-17 04:29 UTC
